### PR TITLE
Feat: Alert component

### PR DESCRIPTION
**Pull request by arulk8**
Description:
Added Alert component.

App link: https://infallible-mccarthy-2a654b.netlify.app/components/alert/

### CODE REVIEW

**Review by harshitpaliwal95 — CHANGES_REQUESTED** [review]
fix side bar z-index
its going behind code snipent
Screenshot 2022-02-07 at 9 59 06 PM

**Comment by harshitpaliwal95** [comment]
overall looks good

**Comment by TJain02** [comment]
Looks good to me.

**Comment by arulk8** [comment]
> overall looks good

made the z-index changes, Thanks

**Pull request merged**
