### PR TITLE
Rating, Simplified Grid , & Toast

### PR DESCRIPTION
**Pull request by arulk8**
Desc: 
1.Fixed linking issues.
2. Added code for Rating, Simplified Grid , & Toast

Rating : https://courageous-cobbler-3f5e05.netlify.app/components/rating/index.html

Grid: https://courageous-cobbler-3f5e05.netlify.app/components/grid/index.html

Toast: https://courageous-cobbler-3f5e05.netlify.app/components/toast/index.html

### CODE REVIEW

**Review by harshitpaliwal95 — APPROVED** [review]
code looks good you can merge

**Review by sashaboi — APPROVED** [review]
image
Hi ! in this code snippet closing div seems to be left out, hope you add them later
Your toast may have a little left padding for better look ? just a suggestion. 
, everything else looks good to merge!

**Comment by arulk8** [comment]
> image Hi ! in this code snippet closing div seems to be left out, hope you add them later Your toast may have a little left padding for better look ? just a suggestion. , everything else looks good to merge!

Yes I left out a div thanks for letting me know.

**Comment by arulk8** [comment]
> image Hi ! in this code snippet closing div seems to be left out, hope you add them later Your toast may have a little left padding for better look ? just a suggestion. , everything else looks good to merge!

I will do the padding changes

**Pull request merged**
